language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools

install:
  - pip install $DJANGO
  - pip install -e .[qa]
  - pip install -U -r requirements-test.txt

before_script:
  - openwisp-utils-qa-checks --migration-path "./tests/test_project/migrations"

script:
  - coverage run --source=openwisp_utils runtests.py

after_success:
  coveralls
